
package util.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MainfestInterfaceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MainfestInterfaceSoap {


    /**
     * 
     * @param voyNo
     * @param wharf
     * @param imo
     * @param shipName
     * @return
     *     returns org.tempuri.ArrayOfShipInfo
     */
    @WebMethod(operationName = "ManifestShipInfo", action = "http://tempuri.org/ManifestShipInfo")
    @WebResult(name = "ManifestShipInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ManifestShipInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ManifestShipInfo")
    @ResponseWrapper(localName = "ManifestShipInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ManifestShipInfoResponse")
    public ArrayOfShipInfo manifestShipInfo(
            @WebParam(name = "shipName", targetNamespace = "http://tempuri.org/")
                    String shipName,
            @WebParam(name = "voyNo", targetNamespace = "http://tempuri.org/")
                    String voyNo,
            @WebParam(name = "imo", targetNamespace = "http://tempuri.org/")
                    String imo,
            @WebParam(name = "wharf", targetNamespace = "http://tempuri.org/")
                    String wharf);

    /**
     * 
     * @param wharf
     * @param containerId
     * @return
     *     returns org.tempuri.ArrayOfContaInfo
     */
    @WebMethod(operationName = "ContainerInfo", action = "http://tempuri.org/ContainerInfo")
    @WebResult(name = "ContainerInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ContainerInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ContainerInfo")
    @ResponseWrapper(localName = "ContainerInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ContainerInfoResponse")
    public ArrayOfContaInfo containerInfo(
            @WebParam(name = "containerId", targetNamespace = "http://tempuri.org/")
                    String containerId,
            @WebParam(name = "wharf", targetNamespace = "http://tempuri.org/")
                    String wharf);

}
